sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build processor-headers
script: ./tests/run.sh
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  
